version: "3.9"

services:
  database:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sleep_management_database_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: sleep_management_db
    expose:
      - "5432"
    ports:
      - "5432:5432"

  sleep_api:
    build: ./sleep/.
    volumes:
      - ./sleep/:/sleep/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/sleep_management_db
      - SPRING_DATASOURCE_USER=sleep_management_database_user
      - SPRING_DATASOURCE_PASSWORD=supersecretpassword
    depends_on:
      - database
